"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.hexadecimalToDecimal = exports.decimalToHexadecimal = exports.getRandomNumber = exports.solveQuadratic = exports.solveLinear = exports.isPrime = exports.factorial = exports.nthRoot = exports.logarithm = void 0;
var math_functions_1 = require("./functions/math.functions");
Object.defineProperty(exports, "logarithm", { enumerable: true, get: function () { return math_functions_1.logarithm; } });
Object.defineProperty(exports, "nthRoot", { enumerable: true, get: function () { return math_functions_1.nthRoot; } });
Object.defineProperty(exports, "factorial", { enumerable: true, get: function () { return math_functions_1.factorial; } });
Object.defineProperty(exports, "isPrime", { enumerable: true, get: function () { return math_functions_1.isPrime; } });
Object.defineProperty(exports, "solveLinear", { enumerable: true, get: function () { return math_functions_1.solveLinear; } });
Object.defineProperty(exports, "solveQuadratic", { enumerable: true, get: function () { return math_functions_1.solveQuadratic; } });
var number_functions_1 = require("./functions/number.functions");
Object.defineProperty(exports, "getRandomNumber", { enumerable: true, get: function () { return number_functions_1.getRandomNumber; } });
Object.defineProperty(exports, "decimalToHexadecimal", { enumerable: true, get: function () { return number_functions_1.decimalToHexadecimal; } });
Object.defineProperty(exports, "hexadecimalToDecimal", { enumerable: true, get: function () { return number_functions_1.hexadecimalToDecimal; } });
